import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import RootClientLayout from "./RootClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://kit.fontawesome.com/aef3aa4adb.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>
      <RootClientLayout geistSans={geistSans.variable} geistMono={geistMono.variable}>
        {children}
      </RootClientLayout>
    </html>
  );
}
